# Generated by Django 3.2.6 on 2021-08-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('gift_donations', models.CharField(max_length=200)),
                ('bills_utilities', models.CharField(max_length=200)),
                ('food_dining', models.CharField(max_length=200)),
                ('health_fitness', models.CharField(max_length=200)),
                ('personal_care', models.CharField(max_length=200)),
                ('fees_charges', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TR', 'travel'), ('ED', 'education'), ('GD', 'gift_donation'), ('BU', 'bill_utilities'), ('FD', 'food_dining'), ('HF', 'health_fitness'), ('PC', 'Personal_care'), ('FC', 'fees_charges')], default=('FC', 'fees_charges'), max_length=200)),
            ],
        ),
    ]
