# Generated by Django 3.2.6 on 2021-08-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=250)),
                ('singer_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=250)),
                ('song_genre', models.CharField(max_length=200)),
                ('song_length', models.DurationField()),
                ('singer', models.ManyToManyField(to='singers.Singer')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField(verbose_name='release date')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singers.song')),
            ],
        ),
    ]
