# Generated by Django 3.2.6 on 2021-08-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='singer',
            old_name='singer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_length',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_name',
            new_name='name',
        ),
    ]
