# Generated by Django 3.2.8 on 2021-10-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_rename_taskname_todolist_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Panding', 'Panding'), ('Progress', 'progress')], max_length=10),
        ),
    ]
