# Generated by Django 3.2.8 on 2021-10-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_alter_todolist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Progress', 'progress')], max_length=10),
        ),
    ]
